import datetime

from pydantic import Field

from .base import Base


class AddCandidateSchema(Base):
    username: str | None = Field(None)
    telegram_id: str = Field(...)
    recruitment_id: str = Field(...)
    nationality: str = Field(...)
    first_name: str = Field(...)
    last_name: str = Field(...)
    patronymic: str = Field(...)
    birthdate: datetime.date = Field(...)
    military_station: str = Field(...)
    military_station_address: str = Field(...)
    university: str = Field(...)
    graduation_date: datetime.date = Field(...)
    direction_training: str = Field(...)
    average_score: float = Field(...)
    find_out: str = Field(...)
    phone_number: str = Field(...)
    subject: str = Field(...)


class GetCandidateSchema(Base):
    id: str = Field(...)
    telegram_id: str = Field(...)
    recruitment_id: str = Field(...)
    nationality: str = Field(...)
    first_name: str = Field(...)
    last_name: str = Field(...)
    patronymic: str = Field(...)
    birthdate: datetime.date = Field(...)
    military_station: str = Field(...)
    military_station_address: str = Field(...)
    university: str = Field(...)
    direction_training: str = Field(...)
    graduation_date: datetime.date = Field(...)
    average_score: float = Field(...)
    find_out: str = Field(...)
    phone_number: str = Field(...)
    subject: str = Field(...)
    is_form: bool = Field(...)
    is_statement: bool = Field(...)
    is_approval: bool = Field(...)


class UpdateCandidateSchema(Base):
    id: str | None = Field(None)
    telegram_id: str | None = Field(None)
    recruitment_id: str | None = Field(None)
    nationality: str | None = Field(None)
    first_name: str | None = Field(None)
    last_name: str | None = Field(None)
    patronymic: str | None = Field(None)
    birthdate: datetime.date | None = Field(None)
    military_station: str | None = Field(None)
    military_station_address: str | None = Field(None)
    university: str | None = Field(None)
    graduation_date: datetime.date | None = Field(None)
    direction_training: str | None = Field(None)
    average_score: float | None = Field(None)
    find_out: str | None = Field(None)
    phone_number: str | None = Field(None)
    subject: str | None = Field(None)


class AddCandidateIDSchema(Base):
    id: str | None = Field(None)
    telegram_id: str | None = Field(None)


class CandidateDocumentNameSchema(Base):
    id: str | None = Field(None)
    telegram_id: str | None = Field(None)
    name: str = Field(...)

class DeleteCandidateSchema(Base):
    candidate_id: str | None = Field(None)

class FormDataSchema(Base):
    candidate_id: str
    telegram_id: str
    first_name: str | None = Field(None)
    last_name: str | None = Field(None)
    patronymic: str | None = Field(None)
    birthplace: str | None = Field(None)
    birthdate: datetime.date | None = Field(None)
    graduation_date: datetime.date | None = Field(None)
    nationality: str | None = Field(None)
    tg_username: str | None = Field(None)
    mail: str | None = Field(None)
    registration_address: str | None = Field(None)
    actual_address: str | None = Field(None)
    family_status: str | None = Field(None)
    military_station: str | None = Field(None)
    health_category: str | None = Field(None)
    university: str | None = Field(None)
    diploma: str | None = Field(None)
    date_issue_diploma: datetime.date | None = Field(None)
    direction_training: str | None = Field(None)
    average_score: float | None = Field(None)
    diploma_topic: str | None = Field(None)
    international_articles: str | None = Field(None)
    patents: str | None = Field(None)
    vac_articles: str | None = Field(None)
    rationalization: str | None = Field(None)
    rinc_articles: str | None = Field(None)
    registration_certificates: str | None = Field(None)
    scientific_work_experience: str | None = Field(None)
    international_olympiads: str | None = Field(None)
    president_scholarship: str | None = Field(None)
    russian_olympiads: str | None = Field(None)
    government_scholarship: str | None = Field(None)
    grant: str | None = Field(None)
    regional_olympiads: str | None = Field(None)
    city_olympiads: str | None = Field(None)
    postgraduate_diploma: str | None = Field(None)
    unused_academic_degree: str | None = Field(None)
    useful_academic_degree: str | None = Field(None)
    commercial_experience: str | None = Field(None)
    OPK_experience: str | None = Field(None)
    exp_research_assistant: str | None = Field(None)
    areas_research: str | None = Field(None)
    programming_languages: str | None = Field(None)
    programs: str | None = Field(None)
    secret: str | None = Field(None)
    height: str | None = Field(None)
    weight: str | None = Field(None)
    sporting_achievements: str | None = Field(None)
    other_sporting_achievements: str | None = Field(None)
    short_run: str | None = Field(None)
    long_run: str | None = Field(None)
    pull_ups: str | None = Field(None)
    chronic_diseases: str | None = Field(None)
    tattoos: str | None = Field(None)
    find_out: str | None = Field(None)

