from aiogram.fsm.state import State, StatesGroup

class AddCandidateState(StatesGroup):
    start = State()
    recruitment = State()
    nationality = State()
    invalid_nationality = State()
    tertiary_education = State()
    invalid_tertiary_education = State()
    birthdate = State()
    subject = State()
    invalid_birthdate = State()
    invalid_period_birthdate = State()
    last_name = State()
    first_name = State()
    graduation_date = State()
    invalid_graduation_date = State()
    patronymic = State()
    military_station = State()
    military_station_address = State()
    university = State()
    direction_training = State()
    average_score = State()
    invalid_average_score = State()
    low_average_score = State()
    find_out = State()
    phone_number = State()
    invalid_phone_number = State()
    check_data = State()
