"""empty message

Revision ID: 822dad8502bb
Revises: b15ad823f79a
Create Date: 2025-11-27 09:53:24.496651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822dad8502bb'
down_revision: Union[str, None] = 'b15ad823f79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegate',
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_delegate_telegram_id'), 'delegate', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_delegate_user_id'), 'delegate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delegate_user_id'), table_name='delegate')
    op.drop_index(op.f('ix_delegate_telegram_id'), table_name='delegate')
    op.drop_table('delegate')
    # ### end Alembic commands ###
