"""empty message

Revision ID: b15ad823f79a
Revises: ad0741174eaf
Create Date: 2025-10-25 12:28:31.833715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15ad823f79a'
down_revision: Union[str, None] = 'ad0741174eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('military_station_address', sa.String(), nullable=False, server_default='Отсутствует'))
    op.add_column('questions', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'number')
    op.drop_column('candidates', 'military_station_address')
    # ### end Alembic commands ###
