"""empty message

Revision ID: 6a8aaffeaeb3
Revises: a6afc27f1930
Create Date: 2025-10-09 09:45:20.705124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8aaffeaeb3'
down_revision: Union[str, None] = 'a6afc27f1930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('subject', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'subject')
    # ### end Alembic commands ###
