"""empty message

Revision ID: a6afc27f1930
Revises: f90afc568d3c
Create Date: 2025-10-08 08:58:19.341164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6afc27f1930'
down_revision: Union[str, None] = 'f90afc568d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['id'])
    op.create_unique_constraint(None, 'candidate_documents', ['id'])
    op.create_unique_constraint(None, 'candidate_quotes', ['id'])
    op.create_unique_constraint(None, 'candidates', ['id'])
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'faq', ['id'])
    op.create_unique_constraint(None, 'info', ['id'])
    op.create_unique_constraint(None, 'promo_documents', ['id'])
    op.create_unique_constraint(None, 'questions', ['id'])
    op.drop_constraint(op.f('questions_user_id_fkey'), 'questions', type_='foreignkey')
    op.create_unique_constraint(None, 'recruitment', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'statuses', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'statuses', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'recruitment', type_='unique')
    op.create_foreign_key(op.f('questions_user_id_fkey'), 'questions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'promo_documents', type_='unique')
    op.drop_constraint(None, 'info', type_='unique')
    op.drop_constraint(None, 'faq', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_constraint(None, 'candidate_quotes', type_='unique')
    op.drop_constraint(None, 'candidate_documents', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
