"""empty message

Revision ID: c4e8a9016876
Revises: 263b42d75a9a
Create Date: 2025-10-17 07:49:28.307431

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4e8a9016876'
down_revision: Union[str, None] = '263b42d75a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'candidate_approvals',
        sa.Column('candidate_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('id', sa.String(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )

    op.create_index(
        op.f('ix_candidate_approvals_candidate_id'),
        'candidate_approvals',
        ['candidate_id'],
        unique=False,
    )

    op.create_index(
        op.f('ix_candidate_approvals_name'),
        'candidate_approvals',
        ['name'],
        unique=False,
    )

    op.rename_table('candidate_documents', 'candidate_forms')

    op.create_table(
        'candidate_statements',
        sa.Column('candidate_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('id', sa.String(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )

    op.create_index(
        op.f('ix_candidate_statements_candidate_id'),
        'candidate_statements',
        ['candidate_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_candidate_statements_name'),
        'candidate_statements',
        ['name'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_candidate_statements_name'),
        table_name='candidate_statements',
    )
    op.drop_index(
        op.f('ix_candidate_statements_candidate_id'),
        table_name='candidate_statements',
    )
    op.drop_table('candidate_statements')
    op.rename_table('candidate_forms', 'candidate_documents')
    op.drop_index(
        op.f('ix_candidate_approvals_name'),
        table_name='candidate_approvals',
    )
    op.drop_index(
        op.f('ix_candidate_approvals_candidate_id'),
        table_name='candidate_approvals',
    )
    op.drop_table('candidate_approvals')
    # ### end Alembic commands ###
