"""empty message

Revision ID: aa6a52972f93
Revises: c4e8a9016876
Create Date: 2025-10-17 08:41:41.141863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6a52972f93'
down_revision: Union[str, None] = 'c4e8a9016876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidate_approvals', ['id'])
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_forms')
    op.drop_index(op.f('ix_candidate_documents_name'), table_name='candidate_forms')
    op.create_index(op.f('ix_candidate_forms_candidate_id'), 'candidate_forms', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_forms_name'), 'candidate_forms', ['name'], unique=False)
    op.create_unique_constraint(None, 'candidate_statements', ['id'])
    op.add_column('candidates', sa.Column('is_form', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('candidates', sa.Column('is_statement', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('candidates', sa.Column('is_approval', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'is_approval')
    op.drop_column('candidates', 'is_statement')
    op.drop_column('candidates', 'is_form')
    op.drop_constraint(None, 'candidate_statements', type_='unique')
    op.drop_index(op.f('ix_candidate_forms_name'), table_name='candidate_forms')
    op.drop_index(op.f('ix_candidate_forms_candidate_id'), table_name='candidate_forms')
    op.create_index(op.f('ix_candidate_documents_name'), 'candidate_forms', ['name'], unique=False)
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_forms', ['candidate_id'], unique=False)
    op.drop_constraint(None, 'candidate_approvals', type_='unique')
    # ### end Alembic commands ###
