"""empty message

Revision ID: 263b42d75a9a
Revises: 6a8aaffeaeb3
Create Date: 2025-10-10 08:55:28.401792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263b42d75a9a'
down_revision: Union[str, None] = '6a8aaffeaeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('graduation_date', sa.Date(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'graduation_date')
    # ### end Alembic commands ###
