"""empty message

Revision ID: f90afc568d3c
Revises: 
Create Date: 2025-10-08 08:56:16.811803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90afc568d3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_quotes',
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('delegate_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_candidate_quotes_delegate_id'), 'candidate_quotes', ['delegate_id'], unique=False)
    op.create_index(op.f('ix_candidate_quotes_subject'), 'candidate_quotes', ['subject'], unique=False)
    op.create_table('candidates',
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('recruitment_id', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('military_station', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('direction_training', sa.String(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('find_out', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_candidates_average_score'), 'candidates', ['average_score'], unique=False)
    op.create_index(op.f('ix_candidates_phone_number'), 'candidates', ['phone_number'], unique=False)
    op.create_index(op.f('ix_candidates_telegram_id'), 'candidates', ['telegram_id'], unique=True)
    op.create_table('faq',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('info',
    sa.Column('about_us_url', sa.String(), nullable=True),
    sa.Column('telegram_channel_url', sa.String(), nullable=True),
    sa.Column('is_info', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_info_about_us_url'), 'info', ['about_us_url'], unique=False)
    op.create_index(op.f('ix_info_telegram_channel_url'), 'info', ['telegram_channel_url'], unique=False)
    op.create_table('recruitment',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('candidate_documents',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_name'), 'candidate_documents', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('info_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['info_id'], ['info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_documents_info_id'), 'documents', ['info_id'], unique=False)
    op.create_table('promo_documents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('info_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['info_id'], ['info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_promo_documents_info_id'), 'promo_documents', ['info_id'], unique=False)
    op.create_table('statuses',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_statuses_candidate_id'), 'statuses', ['candidate_id'], unique=True)
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('questions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('is_answer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_statuses_candidate_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_promo_documents_info_id'), table_name='promo_documents')
    op.drop_table('promo_documents')
    op.drop_index(op.f('ix_documents_info_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_candidate_documents_name'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('recruitment')
    op.drop_index(op.f('ix_info_telegram_channel_url'), table_name='info')
    op.drop_index(op.f('ix_info_about_us_url'), table_name='info')
    op.drop_table('info')
    op.drop_table('faq')
    op.drop_index(op.f('ix_candidates_telegram_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_phone_number'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_average_score'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_quotes_subject'), table_name='candidate_quotes')
    op.drop_index(op.f('ix_candidate_quotes_delegate_id'), table_name='candidate_quotes')
    op.drop_table('candidate_quotes')
    # ### end Alembic commands ###
