"""empty message

Revision ID: 41fe1a6f97dc
Revises: 822dad8502bb
Create Date: 2026-01-27 09:30:43.973609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fe1a6f97dc'
down_revision: Union[str, None] = '822dad8502bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_form_data',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('birthplace', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('registration_address', sa.String(), nullable=True),
    sa.Column('actual_address', sa.String(), nullable=True),
    sa.Column('family_status', sa.String(), nullable=True),
    sa.Column('military_station', sa.String(), nullable=True),
    sa.Column('health_category', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('diploma', sa.String(), nullable=True),
    sa.Column('date_issue_diploma', sa.Date(), nullable=True),
    sa.Column('direction_training', sa.String(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('diploma_topic', sa.String(), nullable=True),
    sa.Column('international_articles', sa.String(), nullable=True),
    sa.Column('patents', sa.String(), nullable=True),
    sa.Column('vac_articles', sa.String(), nullable=True),
    sa.Column('rationalization', sa.String(), nullable=True),
    sa.Column('rinc_articles', sa.String(), nullable=True),
    sa.Column('registration_certificates', sa.String(), nullable=True),
    sa.Column('scientific_work_experience', sa.String(), nullable=True),
    sa.Column('international_olympiads', sa.String(), nullable=True),
    sa.Column('president_scholarship', sa.String(), nullable=True),
    sa.Column('russian_olympiads', sa.String(), nullable=True),
    sa.Column('government_scholarship', sa.String(), nullable=True),
    sa.Column('grant', sa.String(), nullable=True),
    sa.Column('regional_olympiads', sa.String(), nullable=True),
    sa.Column('city_olympiads', sa.String(), nullable=True),
    sa.Column('postgraduate_diploma', sa.String(), nullable=True),
    sa.Column('unused_academic_degree', sa.String(), nullable=True),
    sa.Column('useful_academic_degree', sa.String(), nullable=True),
    sa.Column('commercial_experience', sa.String(), nullable=True),
    sa.Column('OPK_experience', sa.String(), nullable=True),
    sa.Column('exp_research_assistant', sa.String(), nullable=True),
    sa.Column('areas_research', sa.String(), nullable=True),
    sa.Column('programming_languages', sa.String(), nullable=True),
    sa.Column('programs', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('sporting_achievements', sa.String(), nullable=True),
    sa.Column('other_sporting_achievements', sa.String(), nullable=True),
    sa.Column('short_run', sa.String(), nullable=True),
    sa.Column('long_run', sa.String(), nullable=True),
    sa.Column('pull_ups', sa.String(), nullable=True),
    sa.Column('chronic_diseases', sa.String(), nullable=True),
    sa.Column('tattoos', sa.String(), nullable=True),
    sa.Column('find_out', sa.String(), nullable=True),
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_form_data')
    # ### end Alembic commands ###
